#pragma once

#define NO_ACTION_MACRO
#define NO_ACTION_FUN
#define EE_HANDS

#define TAPPING_TERM 190
#define PERMISSIVE_HOLD
#define RETRO_TAPPING

// Neutralize long hold of Alt and GUI keys
#define DUMMY_MOD_NEUTRALIZER_KEYCODE KC_RIGHT_CTRL

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 200

#define WPM_SAMPLE_SECONDS 5
#define WPM_LAUNCH_CONTROL

#define ENCODER_RESOLUTIONS { 6 }
#define ENCODER_RESOLUTIONS_RIGHT { 3 }
