#pragma once

#define NO_ACTION_MACRO
#define NO_ACTION_FUN
#define EE_HANDS

#define TAPPING_TERM 190
// #define RETRO_TAPPING
// #define RETRO_SHIFT
#define PERMISSIVE_HOLD

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 200

#define WPM_SAMPLE_SECONDS 5
#define WPM_LAUNCH_CONTROL
