#pragma once

#define SPLIT_USB_DETECT
#define NO_ACTION_MACRO
#define NO_ACTION_FUN

#define TAPPING_TERM 210
#define RETRO_TAPPING
#define RETRO_SHIFT
#define PERMISSIVE_HOLD

#define NO_AUTO_SHIFT_ALPHA
#define AUTO_SHIFT_TIMEOUT 200

#define WPM_SAMPLE_SECONDS 5
#define WPM_LAUNCH_CONTROL
